modmap:
  - name: global
    remap:
      capslock:
        held: ctrl_l
        alone: esc
        one_timeout_milis: 100
      ctrl_l: # hack :: support physical ctrl -> caps remaps
        held: ctrl_l
        alone: esc
        one_timeout_milis: 100

keymap:
  - name: browser
    application:
      only: firefox
    remap:
      C-n: down # vim :: navigate completion candidates (suggested urls...)
      C-p: up
